# coding: utf-8

"""
    Sources

    Sources  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class OrderParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'service_parameters': 'object',
        'provider_control_parameters': 'object'
    }

    attribute_map = {
        'service_parameters': 'service_parameters',
        'provider_control_parameters': 'provider_control_parameters'
    }

    def __init__(self, service_parameters=None, provider_control_parameters=None):  # noqa: E501
        """OrderParameters - a model defined in OpenAPI"""  # noqa: E501

        self._service_parameters = None
        self._provider_control_parameters = None
        self.discriminator = None

        if service_parameters is not None:
            self.service_parameters = service_parameters
        if provider_control_parameters is not None:
            self.provider_control_parameters = provider_control_parameters

    @property
    def service_parameters(self):
        """Gets the service_parameters of this OrderParameters.  # noqa: E501

        JSON object with provisioning parameters  # noqa: E501

        :return: The service_parameters of this OrderParameters.  # noqa: E501
        :rtype: object
        """
        return self._service_parameters

    @service_parameters.setter
    def service_parameters(self, service_parameters):
        """Sets the service_parameters of this OrderParameters.

        JSON object with provisioning parameters  # noqa: E501

        :param service_parameters: The service_parameters of this OrderParameters.  # noqa: E501
        :type: object
        """

        self._service_parameters = service_parameters

    @property
    def provider_control_parameters(self):
        """Gets the provider_control_parameters of this OrderParameters.  # noqa: E501

        The provider specific parameters needed to provision this service. This might include namespaces, special keys  # noqa: E501

        :return: The provider_control_parameters of this OrderParameters.  # noqa: E501
        :rtype: object
        """
        return self._provider_control_parameters

    @provider_control_parameters.setter
    def provider_control_parameters(self, provider_control_parameters):
        """Sets the provider_control_parameters of this OrderParameters.

        The provider specific parameters needed to provision this service. This might include namespaces, special keys  # noqa: E501

        :param provider_control_parameters: The provider_control_parameters of this OrderParameters.  # noqa: E501
        :type: object
        """

        self._provider_control_parameters = provider_control_parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
