# coding: utf-8

"""
    Sources

    Sources  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Source(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'created_at': 'datetime',
        'id': 'str',
        'name': 'str',
        'source_type_id': 'str',
        'tenant': 'str',
        'uid': 'str',
        'updated_at': 'datetime',
        'version': 'str'
    }

    attribute_map = {
        'created_at': 'created_at',
        'id': 'id',
        'name': 'name',
        'source_type_id': 'source_type_id',
        'tenant': 'tenant',
        'uid': 'uid',
        'updated_at': 'updated_at',
        'version': 'version'
    }

    def __init__(self, created_at=None, id=None, name=None, source_type_id=None, tenant=None, uid=None, updated_at=None, version=None):  # noqa: E501
        """Source - a model defined in OpenAPI"""  # noqa: E501

        self._created_at = None
        self._id = None
        self._name = None
        self._source_type_id = None
        self._tenant = None
        self._uid = None
        self._updated_at = None
        self._version = None
        self.discriminator = None

        if created_at is not None:
            self.created_at = created_at
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if source_type_id is not None:
            self.source_type_id = source_type_id
        if tenant is not None:
            self.tenant = tenant
        if uid is not None:
            self.uid = uid
        if updated_at is not None:
            self.updated_at = updated_at
        if version is not None:
            self.version = version

    @property
    def created_at(self):
        """Gets the created_at of this Source.  # noqa: E501


        :return: The created_at of this Source.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Source.


        :param created_at: The created_at of this Source.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def id(self):
        """Gets the id of this Source.  # noqa: E501

        ID of the resource  # noqa: E501

        :return: The id of this Source.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Source.

        ID of the resource  # noqa: E501

        :param id: The id of this Source.  # noqa: E501
        :type: str
        """
        if id is not None and not re.search(r'^\\d+$', id):  # noqa: E501
            raise ValueError(r"Invalid value for `id`, must be a follow pattern or equal to `/^\\d+$/`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Source.  # noqa: E501


        :return: The name of this Source.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Source.


        :param name: The name of this Source.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def source_type_id(self):
        """Gets the source_type_id of this Source.  # noqa: E501

        ID of the resource  # noqa: E501

        :return: The source_type_id of this Source.  # noqa: E501
        :rtype: str
        """
        return self._source_type_id

    @source_type_id.setter
    def source_type_id(self, source_type_id):
        """Sets the source_type_id of this Source.

        ID of the resource  # noqa: E501

        :param source_type_id: The source_type_id of this Source.  # noqa: E501
        :type: str
        """
        if source_type_id is not None and not re.search(r'^\\d+$', source_type_id):  # noqa: E501
            raise ValueError(r"Invalid value for `source_type_id`, must be a follow pattern or equal to `/^\\d+$/`")  # noqa: E501

        self._source_type_id = source_type_id

    @property
    def tenant(self):
        """Gets the tenant of this Source.  # noqa: E501


        :return: The tenant of this Source.  # noqa: E501
        :rtype: str
        """
        return self._tenant

    @tenant.setter
    def tenant(self, tenant):
        """Sets the tenant of this Source.


        :param tenant: The tenant of this Source.  # noqa: E501
        :type: str
        """

        self._tenant = tenant

    @property
    def uid(self):
        """Gets the uid of this Source.  # noqa: E501


        :return: The uid of this Source.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this Source.


        :param uid: The uid of this Source.  # noqa: E501
        :type: str
        """

        self._uid = uid

    @property
    def updated_at(self):
        """Gets the updated_at of this Source.  # noqa: E501


        :return: The updated_at of this Source.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Source.


        :param updated_at: The updated_at of this Source.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def version(self):
        """Gets the version of this Source.  # noqa: E501


        :return: The version of this Source.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Source.


        :param version: The version of this Source.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Source):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
