# coding: utf-8

"""
    Sources

    Sources  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@redhat.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Tagging(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tag_id': 'str',
        'name': 'str',
        'value': 'str'
    }

    attribute_map = {
        'tag_id': 'tag_id',
        'name': 'name',
        'value': 'value'
    }

    def __init__(self, tag_id=None, name=None, value=None):  # noqa: E501
        """Tagging - a model defined in OpenAPI"""  # noqa: E501

        self._tag_id = None
        self._name = None
        self._value = None
        self.discriminator = None

        if tag_id is not None:
            self.tag_id = tag_id
        if name is not None:
            self.name = name
        if value is not None:
            self.value = value

    @property
    def tag_id(self):
        """Gets the tag_id of this Tagging.  # noqa: E501

        ID of the resource  # noqa: E501

        :return: The tag_id of this Tagging.  # noqa: E501
        :rtype: str
        """
        return self._tag_id

    @tag_id.setter
    def tag_id(self, tag_id):
        """Sets the tag_id of this Tagging.

        ID of the resource  # noqa: E501

        :param tag_id: The tag_id of this Tagging.  # noqa: E501
        :type: str
        """
        if tag_id is not None and not re.search(r'^\\d+$', tag_id):  # noqa: E501
            raise ValueError(r"Invalid value for `tag_id`, must be a follow pattern or equal to `/^\\d+$/`")  # noqa: E501

        self._tag_id = tag_id

    @property
    def name(self):
        """Gets the name of this Tagging.  # noqa: E501


        :return: The name of this Tagging.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Tagging.


        :param name: The name of this Tagging.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """Gets the value of this Tagging.  # noqa: E501


        :return: The value of this Tagging.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Tagging.


        :param value: The value of this Tagging.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tagging):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
