# coding: utf-8

"""
    Sources

    Sources  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sources-api-client
from sources-api-client.models.endpoint import Endpoint  # noqa: E501
from sources-api-client.rest import ApiException


class TestEndpoint(unittest.TestCase):
    """Endpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpoint(self):
        """Test Endpoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sources-api-client.models.endpoint.Endpoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
