# coding: utf-8

"""
    Sources

    Sources  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sources-api-client
from sources-api-client.api.default_api import DefaultApi  # noqa: E501
from sources-api-client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = sources-api-client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_application(self):
        """Test case for create_application

        Create a new Application  # noqa: E501
        """
        pass

    def test_create_authentication(self):
        """Test case for create_authentication

        Create a new Authentication  # noqa: E501
        """
        pass

    def test_create_endpoint(self):
        """Test case for create_endpoint

        Create a new Endpoint  # noqa: E501
        """
        pass

    def test_create_source(self):
        """Test case for create_source

        Create a new Source  # noqa: E501
        """
        pass

    def test_create_source_type(self):
        """Test case for create_source_type

        Create a new SourceType  # noqa: E501
        """
        pass

    def test_delete_application(self):
        """Test case for delete_application

        Delete an existing Application  # noqa: E501
        """
        pass

    def test_delete_authentication(self):
        """Test case for delete_authentication

        Delete an existing Authentication  # noqa: E501
        """
        pass

    def test_delete_endpoint(self):
        """Test case for delete_endpoint

        Delete an existing Endpoint  # noqa: E501
        """
        pass

    def test_delete_source(self):
        """Test case for delete_source

        Delete an existing Source  # noqa: E501
        """
        pass

    def test_get_documentation(self):
        """Test case for get_documentation

        Return this API document in JSON format  # noqa: E501
        """
        pass

    def test_list_application_types(self):
        """Test case for list_application_types

        List ApplicationTypes  # noqa: E501
        """
        pass

    def test_list_applications(self):
        """Test case for list_applications

        List Applications  # noqa: E501
        """
        pass

    def test_list_authentications(self):
        """Test case for list_authentications

        List Authentications  # noqa: E501
        """
        pass

    def test_list_endpoint_authentications(self):
        """Test case for list_endpoint_authentications

        List Authentications for Endpoint  # noqa: E501
        """
        pass

    def test_list_endpoints(self):
        """Test case for list_endpoints

        List Endpoints  # noqa: E501
        """
        pass

    def test_list_source_applications(self):
        """Test case for list_source_applications

        List Applications for Source  # noqa: E501
        """
        pass

    def test_list_source_endpoints(self):
        """Test case for list_source_endpoints

        List Endpoints for Source  # noqa: E501
        """
        pass

    def test_list_source_type_sources(self):
        """Test case for list_source_type_sources

        List Sources for SourceType  # noqa: E501
        """
        pass

    def test_list_source_types(self):
        """Test case for list_source_types

        List SourceTypes  # noqa: E501
        """
        pass

    def test_list_sources(self):
        """Test case for list_sources

        List Sources  # noqa: E501
        """
        pass

    def test_show_application(self):
        """Test case for show_application

        Show an existing Application  # noqa: E501
        """
        pass

    def test_show_application_type(self):
        """Test case for show_application_type

        Show an existing ApplicationType  # noqa: E501
        """
        pass

    def test_show_authentication(self):
        """Test case for show_authentication

        Show an existing Authentication  # noqa: E501
        """
        pass

    def test_show_endpoint(self):
        """Test case for show_endpoint

        Show an existing Endpoint  # noqa: E501
        """
        pass

    def test_show_source(self):
        """Test case for show_source

        Show an existing Source  # noqa: E501
        """
        pass

    def test_show_source_type(self):
        """Test case for show_source_type

        Show an existing SourceType  # noqa: E501
        """
        pass

    def test_update_authentication(self):
        """Test case for update_authentication

        Update an existing Authentication  # noqa: E501
        """
        pass

    def test_update_endpoint(self):
        """Test case for update_endpoint

        Update an existing Endpoint  # noqa: E501
        """
        pass

    def test_update_source(self):
        """Test case for update_source

        Update an existing Source  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
